<?php

namespace app\controllers\base;


use app\components\EntityDB\EntityDB;
use app\models\forms\OrderCreateForm;
use app\models\Tasks;
use app\models\User;
use app\models\Users;
use yii\web\Controller;

class SecuredController extends Controller
{

    public function beforeAction($action)
    {
        if( \Yii::$app->user->isGuest ){
            return $this->redirect(['auth/login']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function getUserRole()
    {
        return \Yii::$app->user->identity->role;
    }

}
