<?php

namespace app\modules\api\controllers\base;


use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;

class Controller extends \yii\web\Controller
{

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator']['class'] = HttpBearerAuth::className();
        //$behaviors['authenticator']['tokenParam'] = 'api_id';
        $behaviors['authenticator']['pattern'] = '/^JWT \s+(.*?)$/';



//        $behaviors[] = [
//            'class' => Cors::className(),
//        ];
        //$behaviors['authenticator']['only'] = ['update'];
        return $behaviors;
    }

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}