<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\web\IdentityInterface;

/**
 * @inheritdoc
 */
class Orders extends \app\models\generated\Orders
{
    const STATUS_WAITING = 1;
    const STATUS_INWORK = 2;
    const STATUS_COMPLETE = 3;



    public function rules()
    {
        return array_merge(
            parent::rules(),
            [

            ]
        );
    }

    public function beforeSave($insert)
    {
        if( $this->isNewRecord ){
            $this->created_at = time();
        }
        $this->updated_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
